name: Snapraid Compile

on:
  # Allow to trigger action manually
  workflow_dispatch:

jobs:
  build_snapraid:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: apt-get update && apt-get -y install dh-autoreconf build-essential jq xz-utils git

    - name: Compile SnapRAID
      run: |
        # Get SnapRAID version and create necessary directories
        SNAPRAID_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} https://api.github.com/repos/amadvance/snapraid/releases/latest | jq -r '.tag_name')
        BUILDDIR=${{ github.workspace }}/$SNAPRAID_V
        PACKAGEDIR=$BUILDDIR/snapraid_package
        mkdir -p $PACKAGEDIR/DEBIAN $PACKAGEDIR/usr/share/doc/mos-snapraid

        # Add initial copyright to package dir:
        echo -e "This package contains software under various licenses.\nSee the following files for details:\n" > $PACKAGEDIR/usr/share/doc/mos-snapraid/copyright

        cd $BUILDDIR
        git clone --branch $SNAPRAID_V --single-branch --depth 1 https://github.com/amadvance/snapraid.git
        cd $BUILDDIR/snapraid
        ./autogen.sh
        ./configure LDFLAGS="-static"
        make -j20
        DESTDIR=$PACKAGEDIR make install

        # Add licenses
        cp "${{ github.workspace }}/LICENSE" "$PACKAGEDIR/usr/share/doc/mos-snapraid/LICENSE"
        echo -e "- LICENSE: License for packaging scripts" >> $PACKAGEDIR/usr/share/doc/mos-snapraid/copyright
        cp $BUILDDIR/snapraid/COPYING $PACKAGEDIR/usr/share/doc/mos-snapraid/LICENSE-snapraid
        echo -e "- LICENSE-snapraid: License for snapraid components" >> $PACKAGEDIR/usr/share/doc/mos-snapraid/copyright
        cp $BUILDDIR/snapraid/tommyds/LICENSE $PACKAGEDIR/usr/share/doc/mos-snapraid/LICENSE-tommyds
        echo -e "- LICENSE-tommyds: License for tommyds components" >> $PACKAGEDIR/usr/share/doc/mos-snapraid/copyright

        cat > $PACKAGEDIR/DEBIAN/control << EOF
        Package: SnapRAID
        Version: ${SNAPRAID_V#v}-mos
        Architecture: amd64
        Maintainer: admin@minenet.at
        Description: Custom SnapRAID build for MOS
        EOF

        cd $BUILDDIR
        chmod -R 755 $PACKAGEDIR
        dpkg-deb --build snapraid_package mos-snapraid_${SNAPRAID_V#v}_amd64.deb
        md5sum $BUILDDIR/mos-snapraid_${SNAPRAID_V#v}_amd64.deb | awk '{print $1}' > $BUILDDIR/mos-snapraid_${SNAPRAID_V#v}_amd64.deb.md5

        echo "SNAPRAID_V=${SNAPRAID_V#v}
        BUILDDIR=$BUILDDIR" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.SNAPRAID_V }}
        release_name: "SnapRAID ${{ env.SNAPRAID_V }}"
        body: |
          This is the custom Debian package from SnapRAID for MOS

          ### Package contents:
          - [SnapRAID](https://github.com/amadvance/snapraid) v${{ env.SNAPRAID_V }}
        draft: false
        prerelease: false

    - name: Upload deb to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.BUILDDIR }}/mos-snapraid_${{ env.SNAPRAID_V }}_amd64.deb
        asset_name: mos-snapraid_${{ env.SNAPRAID_V }}_amd64.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload md5 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.BUILDDIR }}/mos-snapraid_${{ env.SNAPRAID_V }}_amd64.deb.md5
        asset_name: mos-snapraid_${{ env.SNAPRAID_V }}_amd64.deb.md5
        asset_content_type: text/plain

    - name: Set notification variables on success
      if: success()
      run: |
        echo "NOTIFICATION_PRIORITY=0" >> $GITHUB_ENV
        echo "NOTIFICATION_MESSAGE=Built SnapRAID v${{ env.SNAPRAID_V }}" >> $GITHUB_ENV

    - name: Set notification variables on failure
      if: failure()
      run: |
        echo "NOTIFICATION_PRIORITY=1" >> $GITHUB_ENV
        echo "NOTIFICATION_MESSAGE=Failed to build SnapRAID v${{ env.SNAPRAID_V }}" >> $GITHUB_ENV

    - name: Cleanup & Notification
      if: always()
      run: |
        # Discord notification function
        discord_push_notification() {
          if [ $3 -ge 1 ]; then
            COLOR=16711680
          else
            COLOR=65280
          fi

          data=$(cat <<EOF
        {
          "embeds": [{
            "title": "${1}",
            "description": "${2}",
            "color": ${COLOR}
          }]
        }
        EOF
        )
          curl -H "Content-Type: application/json" -d "$data" "${{ secrets.DISCORD_WEBHOOK_URL }}"
        }

        discord_push_notification "${{ github.workflow }}" "${{ env.NOTIFICATION_MESSAGE }}" "${{ env.NOTIFICATION_PRIORITY }}"
        rm -rf ${{ github.workspace }}/* ${{ github.workspace }}/.*
